# New ports collection makefile for: libxbkregex
# Date created: 13 November 2001
# Whom: Boris Koester <koester@x-itec.de>
#
# $FreeBSD$
#
PORTNAME= libxbkregex
PORTVERSION= 1.0
CATEGORIES= devel
MASTER_SITES= http://www.x-itec.de/distfiles/
MAINTAINER= koester@x-itec.de
.include <bsd.port.mk>
